### ISSUE TITLE
Refactor/review permission design

### ISSUE THREAD

**Issue by senyuuri** [SecurityCapstone-2018-Team2/documentation#18]

**Comment by senyuuri** [comment]
Our previous design was like:

1) add patients to ward -> patient inherit ward's permission OR

2) outpatient -> default permission given (by db settings)

As the prof suggested last time, the patient should be the one who has the ultimate control over his own record  so we should not have things like ward permission which could overwrite/affect patients' permission control. Can I propose:

1) Remove ward permission entirely. 

2) The patient should have 3 sets of permission settings:

​	a) the default, applicable only when a new therapist-patient relationship is added. Lowest priority. Default: allow everything

​	b) at individual therapist level, set as attributes in IsAPatientOf. Higher priority. Default: inherit from the default 

​	c) at individual record level, stored in HealthDataPermission. Highest priority, optional. No need to have one for each patient-therapist pair. Default: given by patient 

3) Simplify the permission granularity.  Instead of having image/moive/timeseries access,  just read/forbidden for each permission set. 

4) The default: 

- document owner/issuer can always read/write
- therapist: either can view OR cannot view; do not allow a therapist to modify a record at all time
- by default a user allows all therapists to view all records. He/she can later login to change the setting

**Comment by gabrielsim1993** [comment]
Questions:

> c) at individual record level, stored in HealthDataPermission. Highest priority, optional. No need to have one for each patient-therapist pair. Default: given by patient
- Currently, HealthDataPermission is for every (Patient, Therapist, Data Object). What do you mean by **No need to have one for each patient-therapist pair**

> 4. The default:
> document owner/issuer can always read/write
- Who is the document owner? Therapist or Patient?

> Simplify the permission granularity. Instead of having image/moive/timeseries access, just read/forbidden for each permission set.
- What is permission set here?

**Comment by senyuuri** [comment]
> Currently, HealthDataPermission is for every (Patient, Therapist, Data Object). What do you mean by No need to have one for each patient-therapist pair

It's kind of like a lazy-write strategy. 

When a patient's record is created, there's no need to create a HealthDataPermission immediately for all therapists that are related to this patient . (Imagine we have 100,000 records and each patients has 5 therapists on average, we are saving space for not storing 500,000 duplicated HealthDataPermission.)

Instead, when a therapist wants to view a patient's record:
- If there's a HealthDataPermission for this (patient, therapist, record) combination, use it.
- Else, we fall back to adopt the permission in IsAPatientOf(patient, therapist).

> Who is the document owner? Therapist or Patient?
Maybe owner is not a good word choice.  

The patient is the owner of the his records. He can do what ever he want to the record and give permission for others to view.

The therapist can be an author/creator of a record. He should be able to read/write records that are created by him, unless explicitly forbidden by HealthDataPermission/IsAPatientOf.

> What is permission set here?
I mean the type of permissions we have. There are 3 levels of permissions(default/therapist/record) and at each level we should have only one `isReadable ` flag.

**Comment by gabrielsim1993** [comment]
On which table are permissions going to be stored?

The old design is 
Ward - Default Permissions for new (Patient, Therapist)
IsPatientOf - Default Permissions for new outpatient (Patient, Therapist)
HealthDataPermission - Individual Permission for (Patient, Therapist, Data)

**Comment by senyuuri** [comment]
How about:


Level 0 - Patient - Default Permissions for new (Patient, Therapist)
Level 1 - IsPatientOf - Permissions for (Patient, Therapist).
Level 2 - HealthDataPermission - Individual Permission for (Patient, Therapist, Data)
_(*level = priority lowest-> highest)_
