### ISSUE TITLE
Subsystem 1/2: integrate login API with 2FA tag

### ISSUE THREAD

**Issue by senyuuri** [SecurityCapstone-2018-Team2/documentation#20]

**Comment by nassy93** [comment]
@senyuuri once youre done with the server backend for nonce generation and signature verification/signing, we need to meet to test it!

**Comment by senyuuri** [comment]
> @senyuuri once youre done with the server backend for nonce generation and signature verification/signing, we need to meet to test it!

Okay. I am trying to write a custom django auth backend and integrate `django-two-factor-auth`. Will go look for you tomorrow.
